/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "AdditiveSynth.h"
#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
PlusAudioProcessorEditor::PlusAudioProcessorEditor (PlusAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (220, 200);
    globalAttack.setSliderStyle(Slider::LinearBarVertical);
    globalAttack.setRange(0.01, 10.0, 0.01);
    globalAttack.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalAttack.setPopupDisplayEnabled(true, this);
    globalAttack.setValue(3.0);
    addAndMakeVisible(globalAttack);
    
    globalDecay.setSliderStyle(Slider::LinearBarVertical);
    globalDecay.setRange(0.01, 20.0, 0.01);
    globalDecay.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalDecay.setPopupDisplayEnabled(true, this);
    globalDecay.setValue(1.0);
    addAndMakeVisible(globalDecay);

    globalSustain.setSliderStyle(Slider::LinearBarVertical);
    globalSustain.setRange(0.0, 1.0, 0.01);
    globalSustain.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalSustain.setPopupDisplayEnabled(true, this);
    globalSustain.setValue(0.8);
    addAndMakeVisible(globalSustain);

    globalRelease.setSliderStyle(Slider::LinearBarVertical);
    globalRelease.setRange(0.01, 20.0, 0.01);
    globalRelease.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalRelease.setPopupDisplayEnabled(true, this);
    globalRelease.setValue(1.0);
    addAndMakeVisible(globalRelease);
    
    partialStretch.setSliderStyle(Slider::LinearBarVertical);
    partialStretch.setRange(-0.1, 0.1, 0.0001);
    partialStretch.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    partialStretch.setPopupDisplayEnabled(true, this);
    partialStretch.setValue(0.0);
    addAndMakeVisible(partialStretch);
    
    partialStretchEnvAmt.setSliderStyle(Slider::LinearBarVertical);
    partialStretchEnvAmt.setRange(-0.01, 0.01, 0.0001);
    partialStretchEnvAmt.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    partialStretchEnvAmt.setPopupDisplayEnabled(true, this);
    partialStretchEnvAmt.setValue(0.0);
    addAndMakeVisible(partialStretchEnvAmt);
    
    globalAttack.addListener(this);
    globalDecay.addListener(this);
    globalSustain.addListener(this);
    globalRelease.addListener(this);
    partialStretch.addListener(this);
    partialStretchEnvAmt.addListener(this);
}

PlusAudioProcessorEditor::~PlusAudioProcessorEditor()
{
}

//==============================================================================
void PlusAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("ADSR", 20, 0, 80, 30, Justification::centred, 1);
    g.drawFittedText ("Stretch", 120, 0, 40, 30, Justification::centred, 1);
    g.drawFittedText ("Env", 160, 0, 40, 30, Justification::centred, 1);
}

void PlusAudioProcessorEditor::resized()
{
    globalAttack.setBounds (20, 30, 20, getHeight() - 60);
    globalDecay.setBounds (40, 30, 20, getHeight() - 60);
    globalSustain.setBounds (60, 30, 20, getHeight() - 60);
    globalRelease.setBounds (80, 30, 20, getHeight() - 60);
    partialStretch.setBounds (130, 30, 20, getHeight() - 60);
    partialStretchEnvAmt.setBounds (170, 30, 20, getHeight() - 60);
}

void PlusAudioProcessorEditor::sliderValueChanged(Slider* slider)
{
    if (slider == &globalAttack)
        processor.setParameter(ATTACK, globalAttack.getValue());
    if (slider == &globalDecay)
        processor.setParameter(DECAY, globalDecay.getValue());
    if (slider == &globalSustain)
        processor.setParameter(SUSTAIN, globalSustain.getValue());
    if (slider == &globalRelease)
        processor.setParameter(RELEASE, globalRelease.getValue());
    if (slider == &partialStretch)
    processor.setParameter(STRETCH, partialStretch.getValue());
    if (slider == &partialStretchEnvAmt)
    processor.setParameter(STRETCH_ENV_AMT, partialStretchEnvAmt.getValue());
}
