/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class PlusAudioProcessorEditor  : public AudioProcessorEditor, private Slider::Listener
{
public:
    PlusAudioProcessorEditor (PlusAudioProcessor&);
    ~PlusAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider* slider) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    PlusAudioProcessor& processor;
    
    Slider globalAttack;
    Slider globalDecay;
    Slider globalSustain;
    Slider globalRelease;
    Slider partialStretch;
    Slider partialStretchEnvAmt;
    Slider partialLevelEnvAmt;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PlusAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
