/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
PlusAudioProcessorEditor::PlusAudioProcessorEditor (PlusAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (200, 200);
    globalAttack.setSliderStyle(Slider::LinearBarVertical);
    globalAttack.setRange(0.0, 127.0, 1.0);
    globalAttack.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalAttack.setPopupDisplayEnabled(true, this);
    globalAttack.setValue(1.0);
    addAndMakeVisible(globalAttack);
    
    globalDecay.setSliderStyle(Slider::LinearBarVertical);
    globalDecay.setRange(0.0, 127.0, 1.0);
    globalDecay.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalDecay.setPopupDisplayEnabled(true, this);
    globalDecay.setValue(1.0);
    addAndMakeVisible(globalDecay);

    globalSustain.setSliderStyle(Slider::LinearBarVertical);
    globalSustain.setRange(0.0, 127.0, 1.0);
    globalSustain.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalSustain.setPopupDisplayEnabled(true, this);
    globalSustain.setValue(1.0);
    addAndMakeVisible(globalSustain);

    globalRelease.setSliderStyle(Slider::LinearBarVertical);
    globalRelease.setRange(0.0, 127.0, 1.0);
    globalRelease.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalRelease.setPopupDisplayEnabled(true, this);
    globalRelease.setValue(1.0);
    addAndMakeVisible(globalRelease);
    
}

PlusAudioProcessorEditor::~PlusAudioProcessorEditor()
{
}

//==============================================================================
void PlusAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);

    g.setColour (Colours::black);
    g.setFont (15.0f);
}

void PlusAudioProcessorEditor::resized()
{
    globalAttack.setBounds (40, 30, 20, getHeight() - 60);
    globalDecay.setBounds (60, 30, 20, getHeight() - 60);
    globalRelease.setBounds (80, 30, 20, getHeight() - 60);
    globalSustain.setBounds (100, 30, 20, getHeight() - 60);
}
