/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "AdditiveSynth.h"
#include "PlusAudioProcessorEditor.h"


//==============================================================================
PlusAudioProcessorEditor::PlusAudioProcessorEditor (PlusAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{

    globalAttack.setSliderStyle(Slider::LinearBarVertical);
    globalAttack.setRange(0.01, 10.0, 0.01);
    globalAttack.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalAttack.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(globalAttack);

    globalDecay.setSliderStyle(Slider::LinearBarVertical);
    globalDecay.setRange(0.01, 20.0, 0.01);
    globalDecay.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalDecay.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(globalDecay);

    globalSustain.setSliderStyle(Slider::LinearBarVertical);
    globalSustain.setRange(0.0, 1.0, 0.01);
    globalSustain.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalSustain.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(globalSustain);

    globalRelease.setSliderStyle(Slider::LinearBarVertical);
    globalRelease.setRange(0.01, 20.0, 0.01);
    globalRelease.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    globalRelease.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(globalRelease);

    lfoFrequency.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
    lfoFrequency.setRange(0.01, 100.0, 0.01);
    lfoFrequency.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    lfoFrequency.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(lfoFrequency);

    lfoShape.addItem("Sine",SINE_WAVE_TABLE + 1);
    lfoShape.addItem("Triangle",TRIANGLE_WAVE_TABLE + 1);
    lfoShape.addItem("Saw",SAW_WAVE_TABLE + 1);
    lfoShape.addItem("Ramp",RAMP_WAVE_TABLE + 1);
    lfoShape.setWantsKeyboardFocus(false);
    lfoShape.setItemEnabled(0, false);
    lfoShape.setEditableText(false);
    addAndMakeVisible(lfoShape);

    numberOfVoices.addItem("1",1);
    numberOfVoices.addItem("2",2);
    numberOfVoices.addItem("4",4);
    numberOfVoices.addItem("6",6);
    numberOfVoices.addItem("8",8);
    numberOfVoices.addItem("10",10);
    numberOfVoices.addItem("12",12);
    numberOfVoices.addItem("14",14);
    numberOfVoices.addItem("16",16);
    numberOfVoices.setWantsKeyboardFocus(false);
    numberOfVoices.setItemEnabled(0, false);
    numberOfVoices.setEditableText(false);
    addAndMakeVisible(numberOfVoices);

    for (int i = 0; i < numberOfScales; i++)
    {
        jassert(scales[i].description.isNotEmpty());
        scale.addItem(scales[i].description, i+1);
    }
    scale.setWantsKeyboardFocus(false);
    scale.setEditableText(false);
    addAndMakeVisible(scale);

    scaleRoot.addItem("C",1);
    scaleRoot.addItem("C#",2);
    scaleRoot.addItem("D",3);
    scaleRoot.addItem("D#",4);
    scaleRoot.addItem("E",5);
    scaleRoot.addItem("F",6);
    scaleRoot.addItem("F#",7);
    scaleRoot.addItem("G",8);
    scaleRoot.addItem("G#",9);
    scaleRoot.addItem("A",10);
    scaleRoot.addItem("A#",11);
    scaleRoot.addItem("B",12);
    scaleRoot.setWantsKeyboardFocus(false);
    scaleRoot.setItemEnabled(0, false);
    scaleRoot.setEditableText(false);
    addAndMakeVisible(scaleRoot);

    partialStretch.setSliderStyle(Slider::LinearBarVertical);
    partialStretch.setRange(-1.0, 1.0, 0.01);
    partialStretch.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    partialStretch.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(partialStretch);

    partialStretchFine.setSliderStyle(Slider::LinearBarVertical);
    partialStretchFine.setRange(-0.01, 0.01, 0.0001);
    partialStretchFine.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    partialStretchFine.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(partialStretchFine);

    partialStretchEnvAmt.setSliderStyle(Slider::LinearBarVertical);
    partialStretchEnvAmt.setRange(0.0, 2.0, 0.01);
    partialStretchEnvAmt.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    partialStretchEnvAmt.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(partialStretchEnvAmt);

    partialStretchEnvAmtFine.setSliderStyle(Slider::LinearBarVertical);
    partialStretchEnvAmtFine.setRange(-0.0, 0.1, 0.0001);
    partialStretchEnvAmtFine.setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    partialStretchEnvAmtFine.setPopupDisplayEnabled(true, this);
    addAndMakeVisible(partialStretchEnvAmtFine);

    globalAttack.addListener(this);
    globalDecay.addListener(this);
    globalSustain.addListener(this);
    globalRelease.addListener(this);

    lfoFrequency.addListener(this);
    lfoShape.addListener(this);

    numberOfVoices.addListener(this);
    scale.addListener(this);
    scaleRoot.addListener(this);

    partialStretch.addListener(this);
    partialStretchFine.addListener(this);
    partialStretchEnvAmt.addListener(this);
    partialStretchEnvAmtFine.addListener(this);

    setupPartialComponents(&partialLevel_1, &partialTune_1, &partialPan_1, &partialLfoAmt_1);
    setupPartialComponents(&partialLevel_2, &partialTune_2, &partialPan_2, &partialLfoAmt_2);
    setupPartialComponents(&partialLevel_3, &partialTune_3, &partialPan_3, &partialLfoAmt_3);
    setupPartialComponents(&partialLevel_4, &partialTune_4, &partialPan_4, &partialLfoAmt_4);
    setupPartialComponents(&partialLevel_5, &partialTune_5, &partialPan_5, &partialLfoAmt_5);
    setupPartialComponents(&partialLevel_6, &partialTune_6, &partialPan_6, &partialLfoAmt_6);
    setupPartialComponents(&partialLevel_7, &partialTune_7, &partialPan_7, &partialLfoAmt_7);
    setupPartialComponents(&partialLevel_8, &partialTune_8, &partialPan_8, &partialLfoAmt_8);
    setupPartialComponents(&partialLevel_9, &partialTune_9, &partialPan_9, &partialLfoAmt_9);
    setupPartialComponents(&partialLevel_10, &partialTune_10, &partialPan_10, &partialLfoAmt_10);
    setupPartialComponents(&partialLevel_11, &partialTune_11, &partialPan_11, &partialLfoAmt_11);
    setupPartialComponents(&partialLevel_12, &partialTune_12, &partialPan_12, &partialLfoAmt_12);
    setupPartialComponents(&partialLevel_13, &partialTune_13, &partialPan_13, &partialLfoAmt_13);
    setupPartialComponents(&partialLevel_14, &partialTune_14, &partialPan_14, &partialLfoAmt_14);
    setupPartialComponents(&partialLevel_15, &partialTune_15, &partialPan_15, &partialLfoAmt_15);
    setupPartialComponents(&partialLevel_16, &partialTune_16, &partialPan_16, &partialLfoAmt_16);
    setupPartialComponents(&partialLevel_17, &partialTune_17, &partialPan_17, &partialLfoAmt_17);
    setupPartialComponents(&partialLevel_18, &partialTune_18, &partialPan_18, &partialLfoAmt_18);
    setupPartialComponents(&partialLevel_19, &partialTune_19, &partialPan_19, &partialLfoAmt_19);
    setupPartialComponents(&partialLevel_20, &partialTune_20, &partialPan_20, &partialLfoAmt_20);
    setupPartialComponents(&partialLevel_21, &partialTune_21, &partialPan_21, &partialLfoAmt_21);
    setupPartialComponents(&partialLevel_22, &partialTune_22, &partialPan_22, &partialLfoAmt_22);
    setupPartialComponents(&partialLevel_23, &partialTune_23, &partialPan_23, &partialLfoAmt_23);
    setupPartialComponents(&partialLevel_24, &partialTune_24, &partialPan_24, &partialLfoAmt_24);
    setupPartialComponents(&partialLevel_25, &partialTune_25, &partialPan_25, &partialLfoAmt_25);
    setupPartialComponents(&partialLevel_26, &partialTune_26, &partialPan_26, &partialLfoAmt_26);
    setupPartialComponents(&partialLevel_27, &partialTune_27, &partialPan_27, &partialLfoAmt_27);
    setupPartialComponents(&partialLevel_28, &partialTune_28, &partialPan_28, &partialLfoAmt_28);
    setupPartialComponents(&partialLevel_29, &partialTune_29, &partialPan_29, &partialLfoAmt_29);
    setupPartialComponents(&partialLevel_30, &partialTune_30, &partialPan_30, &partialLfoAmt_30);
    setupPartialComponents(&partialLevel_31, &partialTune_31, &partialPan_31, &partialLfoAmt_31);
    setupPartialComponents(&partialLevel_32, &partialTune_32, &partialPan_32, &partialLfoAmt_32);

    processor.updateUi(true,true);
    timerCallback();
    startTimer(50);
    setSize (910, 370);
}

void PlusAudioProcessorEditor::setupPartialComponents(Slider *level, Slider *tune, Slider *pan, Slider *lfoAmt)
{
    level->setSliderStyle(Slider::LinearBarVertical);
    level->setRange(0.0, 1.0, 0.001);
    level->setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    level->setPopupDisplayEnabled(true, this);
    level->addListener(this);
    addAndMakeVisible(level);

    tune->setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
    tune->setRange(-1.0, 1.0, 0.001);
    tune->setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    tune->setPopupDisplayEnabled(true, this);
    tune->addListener(this);
    addAndMakeVisible(tune);

    pan->setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
    pan->setRange(-1.0, 1.0, 0.001);
    pan->setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    pan->setPopupDisplayEnabled(true, this);
    pan->addListener(this);
    addAndMakeVisible(pan);

    lfoAmt->setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
    lfoAmt->setRange(0.0, 1.0, 0.001);
    lfoAmt->setTextBoxStyle(Slider::NoTextBox, false, 90, 0);
    lfoAmt->setPopupDisplayEnabled(true, this);
    lfoAmt->addListener(this);
    addAndMakeVisible(lfoAmt);
}

PlusAudioProcessorEditor::~PlusAudioProcessorEditor()
{
}

//==============================================================================
void PlusAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("ADSR", 20, 0, 80, 30, Justification::centred, 1);
    g.drawFittedText ("Stretch", 120, 0, 60, 30, Justification::centred, 1);
    g.drawFittedText ("Env", 180, 0, 60, 30, Justification::centred, 1);
    g.drawFittedText ("Partial Levels", 250, 0, 640, 30, Justification::centred, 1);
    g.drawFittedText ("LFO", 200, 238, 60, 30, Justification::centred, 1);
    g.drawFittedText ("Tune", 200, 268, 60, 30, Justification::centred, 1);
    g.drawFittedText ("Pan", 200, 298, 60, 30, Justification::centred, 1);
    g.drawFittedText ("LFO Freq", 20, 238, 60, 30, Justification::centred, 1);
    g.drawFittedText ("LFO Shape", 20, 268, 60, 30, Justification::centred, 1);
    g.drawFittedText ("Voices", 20, 298, 60, 30, Justification::centred, 1);
    g.drawFittedText ("Scale", 20, 328, 60, 30, Justification::centred, 1);
}

void PlusAudioProcessorEditor::resized()
{
    int topRowHeight = 200;
    int topRowTop = 30;
    int lfoRowTop = 245;
    int lfoRowHeight = 20;
    int tuneRowTop = 275;
    int tuneRowHeight = 20;
    int panRowTop = 305;
    int panRowHeight = 20;
    int scaleRowTop = 335;
    int scaleRowHeight = 20;

    globalAttack.setBounds (20, topRowTop, 20, topRowHeight);
    globalDecay.setBounds (40, topRowTop, 20, topRowHeight);
    globalSustain.setBounds (60, topRowTop, 20, topRowHeight);
    globalRelease.setBounds (80, topRowTop, 20, topRowHeight);
    partialStretch.setBounds (130, topRowTop, 20, topRowHeight);
    partialStretchFine.setBounds (150, topRowTop, 20, topRowHeight);
    partialStretchEnvAmt.setBounds (190, topRowTop, 20, topRowHeight);
    partialStretchEnvAmtFine.setBounds (210, topRowTop, 20, topRowHeight);

    layoutPartialComponents(250, topRowTop, &partialLevel_1, &partialTune_1, &partialPan_1, &partialLfoAmt_1);
    layoutPartialComponents(270, topRowTop, &partialLevel_2, &partialTune_2, &partialPan_2, &partialLfoAmt_2);
    layoutPartialComponents(290, topRowTop, &partialLevel_3, &partialTune_3, &partialPan_3, &partialLfoAmt_3);
    layoutPartialComponents(310, topRowTop, &partialLevel_4, &partialTune_4, &partialPan_4, &partialLfoAmt_4);
    layoutPartialComponents(330, topRowTop, &partialLevel_5, &partialTune_5, &partialPan_5, &partialLfoAmt_5);
    layoutPartialComponents(350, topRowTop, &partialLevel_6, &partialTune_6, &partialPan_6, &partialLfoAmt_6);
    layoutPartialComponents(370, topRowTop, &partialLevel_7, &partialTune_7, &partialPan_7, &partialLfoAmt_7);
    layoutPartialComponents(390, topRowTop, &partialLevel_8, &partialTune_8, &partialPan_8, &partialLfoAmt_8);
    layoutPartialComponents(410, topRowTop, &partialLevel_9, &partialTune_9, &partialPan_9, &partialLfoAmt_9);
    layoutPartialComponents(430, topRowTop, &partialLevel_10, &partialTune_10, &partialPan_10, &partialLfoAmt_10);
    layoutPartialComponents(450, topRowTop, &partialLevel_11, &partialTune_11, &partialPan_11, &partialLfoAmt_11);
    layoutPartialComponents(470, topRowTop, &partialLevel_12, &partialTune_12, &partialPan_12, &partialLfoAmt_12);
    layoutPartialComponents(490, topRowTop, &partialLevel_13, &partialTune_13, &partialPan_13, &partialLfoAmt_13);
    layoutPartialComponents(510, topRowTop, &partialLevel_14, &partialTune_14, &partialPan_14, &partialLfoAmt_14);
    layoutPartialComponents(530, topRowTop, &partialLevel_15, &partialTune_15, &partialPan_15, &partialLfoAmt_15);
    layoutPartialComponents(550, topRowTop, &partialLevel_16, &partialTune_16, &partialPan_16, &partialLfoAmt_16);
    layoutPartialComponents(570, topRowTop, &partialLevel_17, &partialTune_17, &partialPan_17, &partialLfoAmt_17);
    layoutPartialComponents(590, topRowTop, &partialLevel_18, &partialTune_18, &partialPan_18, &partialLfoAmt_18);
    layoutPartialComponents(610, topRowTop, &partialLevel_19, &partialTune_19, &partialPan_19, &partialLfoAmt_19);
    layoutPartialComponents(630, topRowTop, &partialLevel_20, &partialTune_20, &partialPan_20, &partialLfoAmt_20);
    layoutPartialComponents(650, topRowTop, &partialLevel_21, &partialTune_21, &partialPan_21, &partialLfoAmt_21);
    layoutPartialComponents(670, topRowTop, &partialLevel_22, &partialTune_22, &partialPan_22, &partialLfoAmt_22);
    layoutPartialComponents(690, topRowTop, &partialLevel_23, &partialTune_23, &partialPan_23, &partialLfoAmt_23);
    layoutPartialComponents(710, topRowTop, &partialLevel_24, &partialTune_24, &partialPan_24, &partialLfoAmt_24);
    layoutPartialComponents(730, topRowTop, &partialLevel_25, &partialTune_25, &partialPan_25, &partialLfoAmt_25);
    layoutPartialComponents(750, topRowTop, &partialLevel_26, &partialTune_26, &partialPan_26, &partialLfoAmt_26);
    layoutPartialComponents(770, topRowTop, &partialLevel_27, &partialTune_27, &partialPan_27, &partialLfoAmt_27);
    layoutPartialComponents(790, topRowTop, &partialLevel_28, &partialTune_28, &partialPan_28, &partialLfoAmt_28);
    layoutPartialComponents(810, topRowTop, &partialLevel_29, &partialTune_29, &partialPan_29, &partialLfoAmt_29);
    layoutPartialComponents(830, topRowTop, &partialLevel_30, &partialTune_30, &partialPan_30, &partialLfoAmt_30);
    layoutPartialComponents(850, topRowTop, &partialLevel_31, &partialTune_31, &partialPan_31, &partialLfoAmt_31);
    layoutPartialComponents(870, topRowTop, &partialLevel_32, &partialTune_32, &partialPan_32, &partialLfoAmt_32);

    lfoFrequency.setBounds (90, lfoRowTop, 20, lfoRowHeight);
    lfoShape.setBounds (90, tuneRowTop, 90, tuneRowHeight);
    numberOfVoices.setBounds (90, panRowTop, 90, panRowHeight);
    scale.setBounds (90, scaleRowTop, 90, scaleRowHeight);
    scaleRoot.setBounds (182, scaleRowTop, 60, scaleRowHeight);
}

void PlusAudioProcessorEditor::layoutPartialComponents(int left, int top, Slider *level, Slider *tune, Slider *pan, Slider *lfoAmt)
{
    int levelHeight = 200;
    int knobHeight = 20;

    level->setBounds (left, top, 20, levelHeight);
    lfoAmt->setBounds (left, top + 215, 20, knobHeight);
    tune->setBounds (left, top + 245, 20, knobHeight);
    pan->setBounds (left, top + 275, 20, knobHeight);
}

void PlusAudioProcessorEditor::sliderValueChanged(Slider* slider)
{
    if (slider == &globalAttack)
        processor.getFloatParam(ATTACK)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &globalDecay)
        processor.getFloatParam(DECAY)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &globalSustain)
        processor.getFloatParam(SUSTAIN)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &globalRelease)
        processor.getFloatParam(RELEASE)->updateProcessorAndHostFromUi(slider->getValue());

    if (slider == &lfoFrequency)
        processor.getFloatParam(LFO_FREQ)->updateProcessorAndHostFromUi(slider->getValue());

    if (slider == &partialStretch)
        processor.getFloatParam(STRETCH)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialStretchFine)
        processor.getFloatParam(STRETCH_FINE)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialStretchEnvAmt)
        processor.getFloatParam(STRETCH_ENV_AMT)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialStretchEnvAmtFine)
        processor.getFloatParam(STRETCH_ENV_AMT_FINE)->updateProcessorAndHostFromUi(slider->getValue());

    if (slider == &partialLevel_1)
        processor.getFloatParam(PARTIAL_1)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_2)
        processor.getFloatParam(PARTIAL_2)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_3)
        processor.getFloatParam(PARTIAL_3)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_4)
        processor.getFloatParam(PARTIAL_4)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_5)
        processor.getFloatParam(PARTIAL_5)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_6)
        processor.getFloatParam(PARTIAL_6)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_7)
        processor.getFloatParam(PARTIAL_7)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_8)
        processor.getFloatParam(PARTIAL_8)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_9)
        processor.getFloatParam(PARTIAL_9)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_10)
        processor.getFloatParam(PARTIAL_10)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_11)
        processor.getFloatParam(PARTIAL_11)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_12)
        processor.getFloatParam(PARTIAL_12)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_13)
        processor.getFloatParam(PARTIAL_13)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_14)
        processor.getFloatParam(PARTIAL_14)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_15)
        processor.getFloatParam(PARTIAL_15)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_16)
        processor.getFloatParam(PARTIAL_16)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_17)
        processor.getFloatParam(PARTIAL_17)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_18)
        processor.getFloatParam(PARTIAL_18)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_19)
        processor.getFloatParam(PARTIAL_19)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_20)
        processor.getFloatParam(PARTIAL_20)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_21)
        processor.getFloatParam(PARTIAL_21)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_22)
        processor.getFloatParam(PARTIAL_22)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_23)
        processor.getFloatParam(PARTIAL_23)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_24)
        processor.getFloatParam(PARTIAL_24)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_25)
        processor.getFloatParam(PARTIAL_25)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_26)
        processor.getFloatParam(PARTIAL_26)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_27)
        processor.getFloatParam(PARTIAL_27)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_28)
        processor.getFloatParam(PARTIAL_28)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_29)
        processor.getFloatParam(PARTIAL_29)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_30)
        processor.getFloatParam(PARTIAL_30)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_31)
        processor.getFloatParam(PARTIAL_31)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLevel_32)
        processor.getFloatParam(PARTIAL_32)->updateProcessorAndHostFromUi(slider->getValue());

    if (slider == &partialTune_1)
        processor.getFloatParam(PARTIAL_TUNE_1)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_2)
        processor.getFloatParam(PARTIAL_TUNE_2)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_3)
        processor.getFloatParam(PARTIAL_TUNE_3)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_4)
        processor.getFloatParam(PARTIAL_TUNE_4)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_5)
        processor.getFloatParam(PARTIAL_TUNE_5)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_6)
        processor.getFloatParam(PARTIAL_TUNE_6)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_7)
        processor.getFloatParam(PARTIAL_TUNE_7)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_8)
        processor.getFloatParam(PARTIAL_TUNE_8)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_9)
        processor.getFloatParam(PARTIAL_TUNE_9)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_10)
        processor.getFloatParam(PARTIAL_TUNE_10)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_11)
        processor.getFloatParam(PARTIAL_TUNE_11)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_12)
        processor.getFloatParam(PARTIAL_TUNE_12)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_13)
        processor.getFloatParam(PARTIAL_TUNE_13)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_14)
        processor.getFloatParam(PARTIAL_TUNE_14)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_15)
        processor.getFloatParam(PARTIAL_TUNE_15)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_16)
        processor.getFloatParam(PARTIAL_TUNE_16)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_17)
        processor.getFloatParam(PARTIAL_TUNE_17)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_18)
        processor.getFloatParam(PARTIAL_TUNE_18)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_19)
        processor.getFloatParam(PARTIAL_TUNE_19)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_20)
        processor.getFloatParam(PARTIAL_TUNE_20)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_21)
        processor.getFloatParam(PARTIAL_TUNE_21)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_22)
        processor.getFloatParam(PARTIAL_TUNE_22)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_23)
        processor.getFloatParam(PARTIAL_TUNE_23)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_24)
        processor.getFloatParam(PARTIAL_TUNE_24)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_25)
        processor.getFloatParam(PARTIAL_TUNE_25)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_26)
        processor.getFloatParam(PARTIAL_TUNE_26)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_27)
        processor.getFloatParam(PARTIAL_TUNE_27)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_28)
        processor.getFloatParam(PARTIAL_TUNE_28)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_29)
        processor.getFloatParam(PARTIAL_TUNE_29)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_30)
        processor.getFloatParam(PARTIAL_TUNE_30)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_31)
        processor.getFloatParam(PARTIAL_TUNE_31)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialTune_32)
        processor.getFloatParam(PARTIAL_TUNE_32)->updateProcessorAndHostFromUi(slider->getValue());

    if (slider == &partialPan_1)
        processor.getFloatParam(PARTIAL_PAN_1)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_2)
        processor.getFloatParam(PARTIAL_PAN_2)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_3)
        processor.getFloatParam(PARTIAL_PAN_3)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_4)
        processor.getFloatParam(PARTIAL_PAN_4)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_5)
        processor.getFloatParam(PARTIAL_PAN_5)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_6)
        processor.getFloatParam(PARTIAL_PAN_6)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_7)
        processor.getFloatParam(PARTIAL_PAN_7)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_8)
        processor.getFloatParam(PARTIAL_PAN_8)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_9)
        processor.getFloatParam(PARTIAL_PAN_9)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_10)
        processor.getFloatParam(PARTIAL_PAN_10)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_11)
        processor.getFloatParam(PARTIAL_PAN_11)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_12)
        processor.getFloatParam(PARTIAL_PAN_12)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_13)
        processor.getFloatParam(PARTIAL_PAN_13)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_14)
        processor.getFloatParam(PARTIAL_PAN_14)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_15)
        processor.getFloatParam(PARTIAL_PAN_15)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_16)
        processor.getFloatParam(PARTIAL_PAN_16)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_17)
        processor.getFloatParam(PARTIAL_PAN_17)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_18)
        processor.getFloatParam(PARTIAL_PAN_18)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_19)
        processor.getFloatParam(PARTIAL_PAN_19)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_20)
        processor.getFloatParam(PARTIAL_PAN_20)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_21)
        processor.getFloatParam(PARTIAL_PAN_21)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_22)
        processor.getFloatParam(PARTIAL_PAN_22)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_23)
        processor.getFloatParam(PARTIAL_PAN_23)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_24)
        processor.getFloatParam(PARTIAL_PAN_24)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_25)
        processor.getFloatParam(PARTIAL_PAN_25)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_26)
        processor.getFloatParam(PARTIAL_PAN_26)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_27)
        processor.getFloatParam(PARTIAL_PAN_27)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_28)
        processor.getFloatParam(PARTIAL_PAN_28)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_29)
        processor.getFloatParam(PARTIAL_PAN_29)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_30)
        processor.getFloatParam(PARTIAL_PAN_30)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_31)
        processor.getFloatParam(PARTIAL_PAN_31)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialPan_32)
        processor.getFloatParam(PARTIAL_PAN_32)->updateProcessorAndHostFromUi(slider->getValue());

    if (slider == &partialLfoAmt_1)
        processor.getFloatParam(PARTIAL_LFO_AMT_1)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_2)
        processor.getFloatParam(PARTIAL_LFO_AMT_2)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_3)
        processor.getFloatParam(PARTIAL_LFO_AMT_3)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_4)
        processor.getFloatParam(PARTIAL_LFO_AMT_4)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_5)
        processor.getFloatParam(PARTIAL_LFO_AMT_5)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_6)
        processor.getFloatParam(PARTIAL_LFO_AMT_6)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_7)
        processor.getFloatParam(PARTIAL_LFO_AMT_7)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_8)
        processor.getFloatParam(PARTIAL_LFO_AMT_8)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_9)
        processor.getFloatParam(PARTIAL_LFO_AMT_9)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_10)
        processor.getFloatParam(PARTIAL_LFO_AMT_10)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_11)
        processor.getFloatParam(PARTIAL_LFO_AMT_11)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_12)
        processor.getFloatParam(PARTIAL_LFO_AMT_12)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_13)
        processor.getFloatParam(PARTIAL_LFO_AMT_13)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_14)
        processor.getFloatParam(PARTIAL_LFO_AMT_14)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_15)
        processor.getFloatParam(PARTIAL_LFO_AMT_15)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_16)
        processor.getFloatParam(PARTIAL_LFO_AMT_16)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_17)
        processor.getFloatParam(PARTIAL_LFO_AMT_17)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_18)
        processor.getFloatParam(PARTIAL_LFO_AMT_18)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_19)
        processor.getFloatParam(PARTIAL_LFO_AMT_19)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_20)
        processor.getFloatParam(PARTIAL_LFO_AMT_20)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_21)
        processor.getFloatParam(PARTIAL_LFO_AMT_21)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_22)
        processor.getFloatParam(PARTIAL_LFO_AMT_22)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_23)
        processor.getFloatParam(PARTIAL_LFO_AMT_23)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_24)
        processor.getFloatParam(PARTIAL_LFO_AMT_24)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_25)
        processor.getFloatParam(PARTIAL_LFO_AMT_25)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_26)
        processor.getFloatParam(PARTIAL_LFO_AMT_26)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_27)
        processor.getFloatParam(PARTIAL_LFO_AMT_27)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_28)
        processor.getFloatParam(PARTIAL_LFO_AMT_28)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_29)
        processor.getFloatParam(PARTIAL_LFO_AMT_29)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_30)
        processor.getFloatParam(PARTIAL_LFO_AMT_30)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_31)
        processor.getFloatParam(PARTIAL_LFO_AMT_31)->updateProcessorAndHostFromUi(slider->getValue());
    if (slider == &partialLfoAmt_32)
        processor.getFloatParam(PARTIAL_LFO_AMT_32)->updateProcessorAndHostFromUi(slider->getValue());

}

void PlusAudioProcessorEditor::comboBoxChanged (ComboBox* comboBox)
{
    if (comboBox == &lfoShape)
        processor.getIntParam(LFO_SHAPE)->updateProcessorAndHostFromUi(comboBox->getSelectedId() - 1);
    if (comboBox == &numberOfVoices)
    {
        processor.getIntParam(NUMBER_OF_VOICES)->updateProcessorAndHostFromUi(comboBox->getSelectedId());
        processor.initVoices();
    }
    if (comboBox == &scale)
        processor.getIntParam(SCALE)->updateProcessorAndHostFromUi(comboBox->getSelectedId() - 1);
    if (comboBox == &scaleRoot)
        processor.getIntParam(SCALE_ROOT)->updateProcessorAndHostFromUi(comboBox->getSelectedId() - 1);
}


void PlusAudioProcessorEditor::timerCallback()
{
    FloatParam *param=processor.getFloatParam(ATTACK);
    if (&globalAttack && param->updateUiRequested()){
        globalAttack.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(DECAY);
    if (&globalDecay && param->updateUiRequested()){
        globalDecay.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(SUSTAIN);
    if (&globalSustain && param->updateUiRequested()){
        globalSustain.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(RELEASE);
    if (&globalRelease && param->updateUiRequested()){
        globalRelease.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(LFO_FREQ);
    if (&lfoFrequency && param->updateUiRequested()){
        lfoFrequency.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(STRETCH);
    if (&partialStretch && param->updateUiRequested()){
        partialStretch.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(STRETCH_FINE);
    if (&partialStretchFine && param->updateUiRequested()){
        partialStretchFine.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(STRETCH_ENV_AMT);
    if (&partialStretchEnvAmt && param->updateUiRequested()){
        partialStretchEnvAmt.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(STRETCH_ENV_AMT_FINE);
    if (&partialStretchEnvAmtFine && param->updateUiRequested()){
        partialStretchEnvAmtFine.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_1);
    if (&partialLevel_1 && param->updateUiRequested()){
        partialLevel_1.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_2);
    if (&partialLevel_2 && param->updateUiRequested()){
        partialLevel_2.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_3);
    if (&partialLevel_3 && param->updateUiRequested()){
        partialLevel_3.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_4);
    if (&partialLevel_4 && param->updateUiRequested()){
        partialLevel_4.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_5);
    if (&partialLevel_5 && param->updateUiRequested()){
        partialLevel_5.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_6);
    if (&partialLevel_6 && param->updateUiRequested()){
        partialLevel_6.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_7);
    if (&partialLevel_7 && param->updateUiRequested()){
        partialLevel_7.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_8);
    if (&partialLevel_8 && param->updateUiRequested()){
        partialLevel_8.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_9);
    if (&partialLevel_9 && param->updateUiRequested()){
        partialLevel_9.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_10);
    if (&partialLevel_10 && param->updateUiRequested()){
        partialLevel_10.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_11);
    if (&partialLevel_11 && param->updateUiRequested()){
        partialLevel_11.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_12);
    if (&partialLevel_12 && param->updateUiRequested()){
        partialLevel_12.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_13);
    if (&partialLevel_13 && param->updateUiRequested()){
        partialLevel_13.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_14);
    if (&partialLevel_14 && param->updateUiRequested()){
        partialLevel_14.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_15);
    if (&partialLevel_15 && param->updateUiRequested()){
        partialLevel_15.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_16);
    if (&partialLevel_16 && param->updateUiRequested()){
        partialLevel_16.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_17);
    if (&partialLevel_17 && param->updateUiRequested()){
        partialLevel_17.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_18);
    if (&partialLevel_18 && param->updateUiRequested()){
        partialLevel_18.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_19);
    if (&partialLevel_19 && param->updateUiRequested()){
        partialLevel_19.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_20);
    if (&partialLevel_20 && param->updateUiRequested()){
        partialLevel_20.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_21);
    if (&partialLevel_21 && param->updateUiRequested()){
        partialLevel_21.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_22);
    if (&partialLevel_22 && param->updateUiRequested()){
        partialLevel_22.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_23);
    if (&partialLevel_23 && param->updateUiRequested()){
        partialLevel_23.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_24);
    if (&partialLevel_24 && param->updateUiRequested()){
        partialLevel_24.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_25);
    if (&partialLevel_25 && param->updateUiRequested()){
        partialLevel_25.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_26);
    if (&partialLevel_26 && param->updateUiRequested()){
        partialLevel_26.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_27);
    if (&partialLevel_27 && param->updateUiRequested()){
        partialLevel_27.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_28);
    if (&partialLevel_28 && param->updateUiRequested()){
        partialLevel_28.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_29);
    if (&partialLevel_29 && param->updateUiRequested()){
        partialLevel_29.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_30);
    if (&partialLevel_30 && param->updateUiRequested()){
        partialLevel_30.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_31);
    if (&partialLevel_31 && param->updateUiRequested()){
        partialLevel_31.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_32);
    if (&partialLevel_32 && param->updateUiRequested()){
        partialLevel_32.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_1);
    if (&partialTune_1 && param->updateUiRequested()){
        partialTune_1.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_2);
    if (&partialTune_2 && param->updateUiRequested()){
        partialTune_2.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_3);
    if (&partialTune_3 && param->updateUiRequested()){
        partialTune_3.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_4);
    if (&partialTune_4 && param->updateUiRequested()){
        partialTune_4.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_5);
    if (&partialTune_5 && param->updateUiRequested()){
        partialTune_5.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_6);
    if (&partialTune_6 && param->updateUiRequested()){
        partialTune_6.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_7);
    if (&partialTune_7 && param->updateUiRequested()){
        partialTune_7.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_8);
    if (&partialTune_8 && param->updateUiRequested()){
        partialTune_8.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_9);
    if (&partialTune_9 && param->updateUiRequested()){
        partialTune_9.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_10);
    if (&partialTune_10 && param->updateUiRequested()){
        partialTune_10.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_11);
    if (&partialTune_11 && param->updateUiRequested()){
        partialTune_11.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_12);
    if (&partialTune_12 && param->updateUiRequested()){
        partialTune_12.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_13);
    if (&partialTune_13 && param->updateUiRequested()){
        partialTune_13.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_14);
    if (&partialTune_14 && param->updateUiRequested()){
        partialTune_14.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_15);
    if (&partialTune_15 && param->updateUiRequested()){
        partialTune_15.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_16);
    if (&partialTune_16 && param->updateUiRequested()){
        partialTune_16.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_17);
    if (&partialTune_17 && param->updateUiRequested()){
        partialTune_17.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_18);
    if (&partialTune_18 && param->updateUiRequested()){
        partialTune_18.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_19);
    if (&partialTune_19 && param->updateUiRequested()){
        partialTune_19.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_20);
    if (&partialTune_20 && param->updateUiRequested()){
        partialTune_20.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_21);
    if (&partialTune_21 && param->updateUiRequested()){
        partialTune_21.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_22);
    if (&partialTune_22 && param->updateUiRequested()){
        partialTune_22.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_23);
    if (&partialTune_23 && param->updateUiRequested()){
        partialTune_23.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_24);
    if (&partialTune_24 && param->updateUiRequested()){
        partialTune_24.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_25);
    if (&partialTune_25 && param->updateUiRequested()){
        partialTune_25.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_26);
    if (&partialTune_26 && param->updateUiRequested()){
        partialTune_26.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_27);
    if (&partialTune_27 && param->updateUiRequested()){
        partialTune_27.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_28);
    if (&partialTune_28 && param->updateUiRequested()){
        partialTune_28.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_29);
    if (&partialTune_29 && param->updateUiRequested()){
        partialTune_29.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_30);
    if (&partialTune_30 && param->updateUiRequested()){
        partialTune_30.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_31);
    if (&partialTune_31 && param->updateUiRequested()){
        partialTune_31.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_TUNE_32);
    if (&partialTune_32 && param->updateUiRequested()){
        partialTune_32.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_1);
    if (&partialPan_1 && param->updateUiRequested()){
        partialPan_1.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_2);
    if (&partialPan_2 && param->updateUiRequested()){
        partialPan_2.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_3);
    if (&partialPan_3 && param->updateUiRequested()){
        partialPan_3.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_4);
    if (&partialPan_4 && param->updateUiRequested()){
        partialPan_4.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_5);
    if (&partialPan_5 && param->updateUiRequested()){
        partialPan_5.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_6);
    if (&partialPan_6 && param->updateUiRequested()){
        partialPan_6.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_7);
    if (&partialPan_7 && param->updateUiRequested()){
        partialPan_7.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_8);
    if (&partialPan_8 && param->updateUiRequested()){
        partialPan_8.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_9);
    if (&partialPan_9 && param->updateUiRequested()){
        partialPan_9.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_10);
    if (&partialPan_10 && param->updateUiRequested()){
        partialPan_10.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_11);
    if (&partialPan_11 && param->updateUiRequested()){
        partialPan_11.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_12);
    if (&partialPan_12 && param->updateUiRequested()){
        partialPan_12.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_13);
    if (&partialPan_13 && param->updateUiRequested()){
        partialPan_13.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_14);
    if (&partialPan_14 && param->updateUiRequested()){
        partialPan_14.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_15);
    if (&partialPan_15 && param->updateUiRequested()){
        partialPan_15.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_16);
    if (&partialPan_16 && param->updateUiRequested()){
        partialPan_16.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_17);
    if (&partialPan_17 && param->updateUiRequested()){
        partialPan_17.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_18);
    if (&partialPan_18 && param->updateUiRequested()){
        partialPan_18.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_19);
    if (&partialPan_19 && param->updateUiRequested()){
        partialPan_19.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_20);
    if (&partialPan_20 && param->updateUiRequested()){
        partialPan_20.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_21);
    if (&partialPan_21 && param->updateUiRequested()){
        partialPan_21.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_22);
    if (&partialPan_22 && param->updateUiRequested()){
        partialPan_22.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_23);
    if (&partialPan_23 && param->updateUiRequested()){
        partialPan_23.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_24);
    if (&partialPan_24 && param->updateUiRequested()){
        partialPan_24.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_25);
    if (&partialPan_25 && param->updateUiRequested()){
        partialPan_25.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_26);
    if (&partialPan_26 && param->updateUiRequested()){
        partialPan_26.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_27);
    if (&partialPan_27 && param->updateUiRequested()){
        partialPan_27.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_28);
    if (&partialPan_28 && param->updateUiRequested()){
        partialPan_28.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_29);
    if (&partialPan_29 && param->updateUiRequested()){
        partialPan_29.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_30);
    if (&partialPan_30 && param->updateUiRequested()){
        partialPan_30.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_31);
    if (&partialPan_31 && param->updateUiRequested()){
        partialPan_31.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_PAN_32);
    if (&partialPan_32 && param->updateUiRequested()){
        partialPan_32.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_1);
    if (&partialLfoAmt_1 && param->updateUiRequested()){
        partialLfoAmt_1.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_2);
    if (&partialLfoAmt_2 && param->updateUiRequested()){
        partialLfoAmt_2.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_3);
    if (&partialLfoAmt_3 && param->updateUiRequested()){
        partialLfoAmt_3.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_4);
    if (&partialLfoAmt_4 && param->updateUiRequested()){
        partialLfoAmt_4.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_5);
    if (&partialLfoAmt_5 && param->updateUiRequested()){
        partialLfoAmt_5.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_6);
    if (&partialLfoAmt_6 && param->updateUiRequested()){
        partialLfoAmt_6.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_7);
    if (&partialLfoAmt_7 && param->updateUiRequested()){
        partialLfoAmt_7.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_8);
    if (&partialLfoAmt_8 && param->updateUiRequested()){
        partialLfoAmt_8.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_9);
    if (&partialLfoAmt_9 && param->updateUiRequested()){
        partialLfoAmt_9.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_10);
    if (&partialLfoAmt_10 && param->updateUiRequested()){
        partialLfoAmt_10.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_11);
    if (&partialLfoAmt_11 && param->updateUiRequested()){
        partialLfoAmt_11.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_12);
    if (&partialLfoAmt_12 && param->updateUiRequested()){
        partialLfoAmt_12.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_13);
    if (&partialLfoAmt_13 && param->updateUiRequested()){
        partialLfoAmt_13.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_14);
    if (&partialLfoAmt_14 && param->updateUiRequested()){
        partialLfoAmt_14.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_15);
    if (&partialLfoAmt_15 && param->updateUiRequested()){
        partialLfoAmt_15.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_16);
    if (&partialLfoAmt_16 && param->updateUiRequested()){
        partialLfoAmt_16.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_17);
    if (&partialLfoAmt_17 && param->updateUiRequested()){
        partialLfoAmt_17.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_18);
    if (&partialLfoAmt_18 && param->updateUiRequested()){
        partialLfoAmt_18.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_19);
    if (&partialLfoAmt_19 && param->updateUiRequested()){
        partialLfoAmt_19.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_20);
    if (&partialLfoAmt_20 && param->updateUiRequested()){
        partialLfoAmt_20.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_21);
    if (&partialLfoAmt_21 && param->updateUiRequested()){
        partialLfoAmt_21.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_22);
    if (&partialLfoAmt_22 && param->updateUiRequested()){
        partialLfoAmt_22.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_23);
    if (&partialLfoAmt_23 && param->updateUiRequested()){
        partialLfoAmt_23.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_24);
    if (&partialLfoAmt_24 && param->updateUiRequested()){
        partialLfoAmt_24.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_25);
    if (&partialLfoAmt_25 && param->updateUiRequested()){
        partialLfoAmt_25.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_26);
    if (&partialLfoAmt_26 && param->updateUiRequested()){
        partialLfoAmt_26.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_27);
    if (&partialLfoAmt_27 && param->updateUiRequested()){
        partialLfoAmt_27.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_28);
    if (&partialLfoAmt_28 && param->updateUiRequested()){
        partialLfoAmt_28.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_29);
    if (&partialLfoAmt_29 && param->updateUiRequested()){
        partialLfoAmt_29.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_30);
    if (&partialLfoAmt_30 && param->updateUiRequested()){
        partialLfoAmt_30.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_31);
    if (&partialLfoAmt_31 && param->updateUiRequested()){
        partialLfoAmt_31.setValue (param->uiGet(), dontSendNotification);
    }
    param=processor.getFloatParam(PARTIAL_LFO_AMT_32);
    if (&partialLfoAmt_32 && param->updateUiRequested()){
        partialLfoAmt_32.setValue (param->uiGet(), dontSendNotification);
    }
    IntParam *intParam = processor.getIntParam(LFO_SHAPE);
    if (&lfoShape && intParam->updateUiRequested()){
        lfoShape.setSelectedId(intParam->uiGet() + 1, dontSendNotification);
    }
    intParam = processor.getIntParam(NUMBER_OF_VOICES);
    if (&numberOfVoices && intParam->updateUiRequested()){
        numberOfVoices.setSelectedId(intParam->uiGet(), dontSendNotification);
    }
    intParam = processor.getIntParam(SCALE);
    if (&scale && intParam->updateUiRequested()){
        scale.setSelectedId(intParam->uiGet(), dontSendNotification);
    }
    intParam = processor.getIntParam(SCALE_ROOT);
    if (&scaleRoot && intParam->updateUiRequested()){
        scaleRoot.setSelectedId(intParam->uiGet(), dontSendNotification);
    }
}
