/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PlusAudioProcessor.h"


//==============================================================================
/**
*/
class PlusAudioProcessorEditor  : public AudioProcessorEditor, private Slider::Listener, public Timer
{
public:
    PlusAudioProcessorEditor (PlusAudioProcessor&);
    ~PlusAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider* slider) override;
    void timerCallback();

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    PlusAudioProcessor& processor;

    Slider globalAttack;
    Slider globalDecay;
    Slider globalSustain;
    Slider globalRelease;
    Slider partialStretch;
    Slider partialStretchFine;
    Slider partialStretchEnvAmt;
    Slider partialStretchEnvAmtFine;
    Slider partialLevel_1;
    Slider partialLevel_2;
    Slider partialLevel_3;
    Slider partialLevel_4;
    Slider partialLevel_5;
    Slider partialLevel_6;
    Slider partialLevel_7;
    Slider partialLevel_8;
    Slider partialLevel_9;
    Slider partialLevel_10;
    Slider partialLevel_11;
    Slider partialLevel_12;
    Slider partialLevel_13;
    Slider partialLevel_14;
    Slider partialLevel_15;
    Slider partialLevel_16;
    Slider partialLevel_17;
    Slider partialLevel_18;
    Slider partialLevel_19;
    Slider partialLevel_20;
    Slider partialLevel_21;
    Slider partialLevel_22;
    Slider partialLevel_23;
    Slider partialLevel_24;
    Slider partialLevel_25;
    Slider partialLevel_26;
    Slider partialLevel_27;
    Slider partialLevel_28;
    Slider partialLevel_29;
    Slider partialLevel_30;
    Slider partialLevel_31;
    Slider partialLevel_32;
    Slider partialLevelEnvAmt;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PlusAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
